#!/bin/sh
# modify_examples - script for testing the modify script

# First, create a directory tree and display it
echo "-----------------------------------"
echo "Creating directory tree for testing"

mkdir "test"
cd "test"
mkdir "dir"
mkdir "directory"
mkdir "folder"
mkdir "dir/inside"
mkdir "dir/inside/deep"
mkdir "dir/another"
mkdir "directory/elephant"
mkdir "directory/giraffe"
ls -R

# Then, use the script in different ways and display results

# showing -h
echo "-----------------------------------"
echo "Running modify -h"
../modify -h

# Correct usage
echo "-----------------------------------"
echo "Correct examples:"
echo "Running modify -u directory folder"
../modify -u directory folder
ls -R

echo "-----------------------------------"
echo "Running modify -l DIRECTORY"
../modify -l DIRECTORY
ls -R

echo "-----------------------------------"
echo "Running modify 's/di/SED/' dir FOLDER"
../modify 's/di/SED/' dir FOLDER
ls -R

echo "-----------------------------------"
echo "Running modify -r -u SEDr"
../modify -r -u SEDr
ls -R

echo "-----------------------------------"
echo "Running modify -r -l SEDR"
../modify -r -l SEDR
ls -R

echo "-----------------------------------"
echo "Running modify -r 's/e/EOPSY/' directory"
../modify -r 's/r/EOPSY/' directory
ls -R

#Incorrect usage
echo "-----------------------------------"
echo "Running modify -d"
../modify -d

echo "-----------------------------------"
echo "Running modify -l -u FOLDER"
../modify -l -u FOLDER
ls

echo "-----------------------------------"
echo "Running modify -r 's/[a-z]/1/g'"
../modify -r 's/[a-z]/1/g'
ls

# After finished, clean up
echo "-----------------------------------"
echo "Cleaning up the test directory tree"
cd ..
rm -r "test"
